name: Magnetize CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  magnetize-ci:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.9
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: magnetize_test
          MYSQL_USER: magnetize
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3 # Update to your Laravel version's PHP requirement
          extensions: mbstring, pdo_mysql, bcmath, intl
          coverage: none

      # Install composer dependencies
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Setup application
      - name: Setup Laravel
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --seed --force

      # Run tests
      - name: Run Tests
        run: php artisan test
