name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: magnetize_test
          MARIADB_USER: magnetize
          MARIADB_PASSWORD: password
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3 # Update to your Laravel version's PHP requirement
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Ensure this matches the version your project uses

      # Install composer dependencies
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm install

      # Build assets using Vite
      - name: Build assets
        run: npm run build

      # Setup application
      - name: Setup Laravel
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan migrate --seed --force

      # Run tests
      - name: Run Tests
        run: php artisan test
